// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bycdugukzlinjiptxfpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5Y2R1Z3VremxpbmppcHR4ZnB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5NzgxMjAsImV4cCI6MjA4NjU1NDEyMH0.HZaTla6w7gbp1aMQ4Dup778qjZlW4lD_cp8j0AllTlw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});